import { useEffect, useState } from 'react';
import { DEFAULT_SETTINGS, DEFAULT_SYNC_STATUS, type Settings, type SyncStatus } from '../lib/types';
import './style.css';
export default function App() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS); const [status, setStatus] = useState<SyncStatus>(DEFAULT_SYNC_STATUS);
  useEffect(() => { void chrome.storage.local.get(['settings', 'syncStatus']).then(data => { setSettings(data.settings ?? DEFAULT_SETTINGS); setStatus(data.syncStatus ?? DEFAULT_SYNC_STATUS); }); void chrome.runtime.sendMessage({ type: 'CODESYNC_AUTH_STATUS' }).catch(() => undefined); const onChanged = (changes: { [key: string]: chrome.storage.StorageChange }, area: string) => { if (area === 'local') { if (changes.settings?.newValue) setSettings(changes.settings.newValue as Settings); if (changes.syncStatus?.newValue) setStatus(changes.syncStatus.newValue as SyncStatus); } }; chrome.storage.onChanged.addListener(onChanged); return () => chrome.storage.onChanged.removeListener(onChanged); }, []);
  async function toggle() { const next = { ...settings, enabled: !settings.enabled }; setSettings(next); await chrome.storage.local.set({ settings: next }); }
  async function retry() { await chrome.runtime.sendMessage({ type: 'CODESYNC_RETRY_NOW' }); const { syncStatus } = await chrome.storage.local.get('syncStatus'); setStatus(syncStatus ?? DEFAULT_SYNC_STATUS); }
  async function retryFailed() { await chrome.runtime.sendMessage({ type: 'CODESYNC_RETRY_FAILED_SUBMISSIONS' }); const { syncStatus } = await chrome.storage.local.get('syncStatus'); setStatus(syncStatus ?? DEFAULT_SYNC_STATUS); }
  const counts = status.counts ?? { pending: status.pending, retrying: 0, committed: 0, permanentlyFailed: 0 };
  return <main><header><h1>⚡ CodeSync</h1><span className="pill">Phase 3</span></header><p>Competitive programming → GitHub</p><section><div className="between"><strong>Extension</strong><button onClick={() => void toggle()}>{settings.enabled ? 'Enabled' : 'Paused'}</button></div><p>{status.message}</p><p>Pending: {counts.pending} · Retrying: {counts.retrying} · Committed: {counts.committed} · Failed: {counts.permanentlyFailed}</p>{status.latestGitHubError && <p>Latest GitHub error: {status.latestGitHubError}</p>}{status.pending > 0 && <button onClick={() => void retry()}>Retry queue ({status.pending})</button>}{counts.permanentlyFailed > 0 && <button onClick={() => void retryFailed()}>Retry failed submissions ({counts.permanentlyFailed})</button>}</section><section><strong>Target repository</strong><p>{settings.repository || 'Not configured'}</p><button onClick={() => chrome.runtime.openOptionsPage()}>Open settings</button></section><small>LeetCode · Codeforces · CodeChef · CSES · AtCoder</small></main>;
}
